const router = require("express").Router();
const user = require("./user.index");
const board = require("./board.index");
const comment = require("./comment.index");
const auth = require("./auth.index");
const { Board } = require("../models");
router.use("/user", user);
router.use("/board", board);
router.use("/board/:boardId/comment", comment);
router.use("/auth", auth);
module.exports = router;
